version: '3.3'
services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'oktan-agc'
            MYSQL_USER: 'oktan-agc'
            MYSQL_PASSWORD: 'oktan-agc'
            MYSQL_ROOT_PASSWORD: 'oktan-agc'
        ports:
            - '3307:3306'
        expose:
            - '3306'
        volumes:
            - oktan-agc-db:/var/lib/mysql
volumes:
    oktan-agc-db:
